'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'bn' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  bn: {
    // Navigation
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.courses': 'কোর্স',
    'nav.batches': 'ব্যাচ',
    'nav.students': 'শিক্ষার্থী',
    'nav.teachers': 'শিক্ষক',
    'nav.guardians': 'অভিভাবক',
    'nav.exams': 'পরীক্ষা',
    'nav.payments': 'পেমেন্ট',
    'nav.analytics': 'বিশ্লেষণ',
    'nav.logout': 'লগআউট',
    'nav.search': 'সার্চ করুন...',
    
    // Dashboard
    'dashboard.title': 'ড্যাশবোর্ড',
    'dashboard.subtitle': 'আপনার শিক্ষা প্রতিষ্ঠানের সামগ্রিক overview',
    'dashboard.totalStudents': 'মোট শিক্ষার্থী',
    'dashboard.totalTeachers': 'মোট শিক্ষক',
    'dashboard.totalCourses': 'মোট কোর্স',
    'dashboard.totalRevenue': 'মোট আয়',
    'dashboard.activeBatches': 'চলমান ব্যাচ',
    'dashboard.upcomingExams': 'আসন্ন পরীক্ষা',
    'dashboard.pendingPayments': 'বকেয়া পেমেন্ট',
    'dashboard.recentActivities': 'সাম্প্রতিক কার্যক্রম',
    'dashboard.notices': 'বিজ্ঞপ্তি',
    'dashboard.popularCourses': 'জনপ্রিয় কোর্স',
    'dashboard.newStudents': 'নতুন শিক্ষার্থী',
    'dashboard.viewAll': 'সব দেখুন',
    
    // Common
    'common.add': 'যোগ করুন',
    'common.edit': 'এডিট',
    'common.delete': 'মুছুন',
    'common.view': 'দেখুন',
    'common.save': 'সংরক্ষণ',
    'common.cancel': 'বাতিল',
    'common.search': 'সার্চ',
    'common.filter': 'ফিল্টার',
    'common.actions': 'অ্যাকশন',
    'common.status': 'স্ট্যাটাস',
    'common.active': 'সক্রিয়',
    'common.inactive': 'নিষ্ক্রিয়',
    'common.pending': 'বকেয়া',
    'common.completed': 'সম্পন্ন',
    'common.upcoming': 'আসন্ন',
    'common.all': 'সব',
    'common.details': 'বিস্তারিত',
    'common.create': 'তৈরি করুন',
    'common.admin': 'প্রশাসক',
    
    // Courses
    'courses.title': 'কোর্স ম্যানেজমেন্ট',
    'courses.subtitle': 'আপনার সকল কোর্স এখানে পরিচালনা করুন',
    'courses.newCourse': 'নতুন কোর্স',
    'courses.published': 'প্রকাশিত',
    'courses.draft': 'খসড়া',
    'courses.featured': 'ফিচার্ড',
    'courses.hsc': 'এইচএসসি',
    'courses.ssc': 'এসএসসি',
    'courses.admission': 'ভর্তি প্রস্তুতি',
    'courses.job': 'চাকরি',
    'courses.skill': 'দক্ষতা',
    'courses.language': 'ভাষা',
    'courses.allCourses': 'সব কোর্স',
    'courseName': 'কোর্সের নাম',
    'category': 'ক্যাটাগরি',
    'price': 'মূল্য',
    'discount': 'ডিসকাউন্ট',
    'subject': 'বিষয়',
    'totalClasses': 'মোট ক্লাস',
    'students': 'শিক্ষার্থী',
    'enrolled': 'ভর্তি',
    
    // Batches
    'batches.title': 'ব্যাচ ম্যানেজমেন্ট',
    'batches.subtitle': 'আপনার সকল ব্যাচ এখানে পরিচালনা করুন',
    'batches.newBatch': 'নতুন ব্যাচ',
    'batches.ongoing': 'চলমান',
    'batches.allBatches': 'সব ব্যাচ',
    'batchName': 'ব্যাচের নাম',
    'schedule': 'সপ্তাহের দিন',
    'room': 'রুম',
    'startDate': 'শুরু',
    'endDate': 'শেষ',
    'maxStudents': 'সর্বোচ্চ',
    'current': 'বর্তমান',
    'sat': 'শনি',
    'sun': 'রবি',
    'mon': 'সোম',
    'tue': 'মঙ্গল',
    'wed': 'বুধ',
    'thu': 'বৃহস্পতি',
    'fri': 'শুক্র',
    
    // Students
    'students.title': 'শিক্ষার্থী ম্যানেজমেন্ট',
    'students.subtitle': 'আপনার সকল শিক্ষার্থী এখানে পরিচালনা করুন',
    'students.newStudent': 'নতুন শিক্ষার্থী',
    'studentName': 'নাম',
    'roll': 'রোল',
    'class': 'শ্রেণী',
    'group': 'গ্রুপ',
    'session': 'সেশন',
    'email': 'ইমেইল',
    'phone': 'ফোন',
    'allStudents': 'সব শিক্ষার্থী',
    'suspended': 'স্থগিত',
    
    // Teachers
    'teachers.title': 'শিক্ষক ম্যানেজমেন্ট',
    'teachers.subtitle': 'আপনার শিক্ষকদের প্রোফাইল ও তথ্য পরিচালনা করুন',
    'teachers.newTeacher': 'নতুন শিক্ষক',
    'qualification': 'যোগ্যতা',
    'experience': 'অভিজ্ঞতা',
    'designation': 'পদবি',
    'years': 'বছর',
    
    // Guardian
    'guardian.title': 'অভিভাবক ম্যানেজমেন্ট',
    'guardian.subtitle': 'শিক্ষার্থীদের অভিভাবকদের তথ্য পরিচালনা করুন',
    'guardian.newGuardian': 'নতুন অভিভাবক',
    'occupation': 'পেশা',
    'relation': 'সম্পর্ক',
    'father': 'বাবা',
    'mother': 'মা',
    'other': 'অন্যান্য',
    'children': 'সন্তান',
    'monthlyIncome': 'মাসিক আয়',
    
    // Exams
    'exams.title': 'পরীক্ষা ম্যানেজমেন্ট',
    'exams.subtitle': 'আপনার সকল পরীক্ষা এখানে পরিচালনা করুন',
    'exams.newExam': 'নতুন পরীক্ষা',
    'examType': 'টাইপ',
    'mcq': 'MCQ',
    'written': 'লিখিত',
    'practical': 'ব্যবহারিক',
    'mixed': 'মিশ্র',
    'totalMarks': 'মোট নম্বর',
    'passingMarks': 'পাস নম্বর',
    'duration': 'সময়সীমা',
    'minutes': 'মিনিট',
    'startExam': 'পরীক্ষা শুরু',
    'result': 'ফলাফল',
    'questions': 'প্রশ্ন',
    
    // Payments
    'payments.title': 'পেমেন্ট ম্যানেজমেন্ট',
    'payments.subtitle': 'শিক্ষার্থীদের পেমেন্ট ট্র্যাক করুন',
    'payments.newPayment': 'নতুন পেমেন্ট',
    'amount': 'পরিমাণ',
    'method': 'মাধ্যম',
    'transactionId': 'ট্রানজেকশন',
    'date': 'তারিখ',
    'due': 'Due',
    'bkash': 'বিকাশ',
    'nagad': 'নগদ',
    'rocket': 'রকেট',
    'bank': 'ব্যাংক',
    'cash': 'ক্যাশ',
    'card': 'কার্ড',
    'admissionFee': 'ভর্তি ফি',
    'monthlyFee': 'মাসিক বেতন',
    'examFee': 'পরীক্ষা ফি',
    'certificateFee': 'সনদপত্র ফি',
    'otherFee': 'অন্যান্য',
    'failed': 'ব্যর্থ',
    'refunded': 'ফেরত',
    'receipt': 'রসিদ',
    'remind': 'রিমাইন্ড',
    'mark': 'মার্ক',
    
    // Analytics
    'analytics.title': 'অ্যানালিটিক্স',
    'analytics.subtitle': 'আপনার প্রতিষ্ঠানের বিস্তারিত বিশ্লেষণ',
    'thisMonth': 'এই মাস',
    'thisYear': 'এই বছর',
    'monthlyRevenue': 'মাসিক আয়',
    'attendanceRate': 'উপস্থিতি হার',
    'avgScore': 'গড় স্কোর',
    'passRate': 'পাস রেট',
    'topCourses': 'সেরা কোর্স',
    'enrollmentByCategory': 'ক্যাটাগরি অনুযায়ী শিক্ষার্থী',
    'examTrend': 'পরীক্ষার ফলাফল ট্রেন্ড',
    'avgScoreShort': 'গড়',
    'passRateShort': 'পাস',
    'term': 'টার্ম',
    'avgRevenue': 'গড় আয়',
    
    // Auth
    'auth.welcome': 'স্বাগতম!',
    'auth.loginTitle': 'আপনার অ্যাকাউন্টে লগইন করুন',
    'auth.registerTitle': 'রেজিস্ট্রেশন করুন',
    'auth.loginSubtitle': 'বিনামূল্যে আজই শুরু করুন',
    'auth.login': 'লগইন করুন',
    'auth.register': 'রেজিস্ট্রেশন করুন',
    'auth.noAccount': 'অ্যাকাউন্ট নেই?',
    'auth.hasAccount': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    'auth.registerNow': 'এখনই রেজিস্টার করুন',
    'auth.loginNow': 'লগইন করুন',
    'auth.or': 'অথবা',
    'auth.remember': 'মনে রাখুন',
    'auth.forgotPassword': 'পাসওয়ার্ড ভুলে গেছেন?',
    'auth.terms': 'শর্তাবলী',
    'auth.privacy': 'গোপনীয়তা নীতি',
    'auth.agree': 'আমি পড়েছি এবং একমত।',
    'auth.whoAreYou': 'আপনি কে?',
    'auth.student': 'শিক্ষার্থী',
    'auth.teacher': 'শিক্ষক',
    'auth.guardian': 'অভিভাবক',
    'auth.confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
    
    // Landing
    'landing.heroTitle': 'বাংলাদেশের সেরা',
    'landing.heroSubtitle': 'অনলাইন শিক্ষা প্ল্যাটফর্ম',
    'landing.heroDesc': 'এইচএসসি, এসএসসি, বিশ্ববিদ্যালয় ভর্তি, বিসিএস এবং চাকরি পরীক্ষার জন্য বাংলায় সম্পূর্ণ প্রস্তুতি। দেশের শীর্ষ শিক্ষকদের পাঠে নিজেকে আরও দক্ষ করে তুলুন।',
    'landing.startFree': 'বিনামূল্যে শুরু করুন',
    'landing.viewCourses': 'কোর্স দেখুন',
    'landing.studentsEnrolled': 'শিক্ষার্থী সফলভাবে কোর্স সম্পন্ন করেছে',
    'landing.whyChoose': 'কেন বেছে নেবেন?',
    'landing.whyDesc': 'আমরা বাংলাদেশের শিক্ষার্থীদের জন্য সর্বোত্তম শিক্ষা অভিজ্ঞতা নিশ্চিত করতে প্রতিশ্রুতিবদ্ধ',
    'landing.banglaCourse': 'বাংলায় কোর্স',
    'landing.banglaDesc': 'সব কন্টেন্ট বাংলায়, যা বাংলাদেশের শিক্ষার্থীদের জন্য সহজে বোধগম্য',
    'landing.onlineOffline': 'অনলাইন + অফলাইন',
    'landing.onlineOfflineDesc': 'লাইভ ক্লাস এবং রেকর্ডেড ভিডিও, যেখানে ইন্টারনেট সংযোগ নেই সেখানেও পড়ুন',
    'landing.modernTest': 'মডার্ন টেস্ট',
    'landing.modernTestDesc': 'বোর্ড প্যাটার্ন অনুযায়ী মডেল টেস্ট এবং কুইজের মাধ্যমে প্রস্তুতি নিন',
    'landing.expertTeachers': 'এক্সপার্ট শিক্ষক',
    'landing.expertDesc': 'দেশের সেরা বিশ্ববিদ্যালয় এবং কোচিং সেন্টারের অভিজ্ঞ শিক্ষক',
    'landing.affordable': 'সাশ্রয়ী মূল্য',
    'landing.affordableDesc': 'সেরা মানের শিক্ষা সবার নাগালের মধ্যে, বিকাশ/নগদে পেমেন্ট',
    'landing.certificate': 'সার্টিফিকেট',
    'landing.certificateDesc': 'কোর্স সম্পন্ন করে প্রত্যয়নপত্র পান যা চাকরির বাজারে মূল্যবান',
    'landing.popularCourses': 'জনপ্রিয় কোর্সসমূহ',
    'landing.popularDesc': 'আমাদের সেরা কোর্সগুলো দেখুন এবং আজই শুরু করুন',
    'landing.viewAllCourses': 'সব কোর্স দেখুন',
    'landing.ourTeachers': 'আমাদের শিক্ষক মণ্ডলী',
    'landing.teachersDesc': 'বাংলাদেশের সেরা বিশ্ববিদ্যালয় এবং কোচিং সেন্টারের অভিজ্ঞ শিক্ষকরা আপনার পড়াশোনায় গাইড হিসেবে কাজ করছেন',
    'landing.startJourney': 'আজই আপনার শিক্ষা যাত্রা শুরু করুন',
    'landing.journeyDesc': 'হাজার হাজার শিক্ষার্থী ইতিমধ্যে আমাদের কোর্সে সফল হয়েছে। এবার আপনার পালা!',
    'landing.registerFree': 'বিনামূল্যে রেজিস্ট্রেশন করুন',
    'landing.watchDemo': 'ডেমো দেখুন',
    'landing.courses': 'কোর্স',
    'landing.about': 'আমাদের সম্পর্কে',
    'landing.contact': 'যোগাযোগ',
    'landing.login': 'লগইন',
    'landing.freeStart': 'বিনামূল্যে শুরু করুন',
    
    // Footer
    'footer.about': 'বাংলাদেশের সেরা অনলাইন শিক্ষা প্ল্যাটফর্ম। HSC, SSC, University Admission এবং Job Preparation এর জন্য সম্পূর্ণ প্রস্তুতি।',
    'footer.hsc': 'এইচএসসি প্রস্তুতি',
    'footer.ssc': 'এসএসসি প্রস্তুতি',
    'footer.admission': 'বিশ্ববিদ্যালয় ভর্তি',
    'footer.bcs': 'বিসিএস প্রস্তুতি',
    'footer.becomeTeacher': 'শিক্ষক হন',
    'footer.privacy': 'প্রাইভেসি পলিসি',
    'footer.terms': 'টার্মস অব সার্ভিস',
    'footer.contact': 'যোগাযোগ',
    'footer.cookies': 'কুকি সেটিংস',
    'footer.copyright': 'সর্বস্বত্ব সংরক্ষিত।',
    'footer.hscCourses': 'HSC প্রস্তুতি',
    'footer.important': 'গুরুত্বপূর্ণ লিংক',
    'footer.address': 'ঢাকা, বাংলাদেশ',
    
    // Notice types
    'notice.general': 'সাধারণ',
    'notice.exam': 'পরীক্ষা',
    'notice.payment': 'পেমেন্ট',
    'notice.event': 'ইভেন্ট',
    'notice.holiday': 'ছুটি',
    'notice.urgent': 'জরুরি',
    'notice.high': 'উচ্চ',
    'notice.medium': 'মাঝারি',
    'notice.low': 'কম',
    
    // Settings
    'settings.language': 'ভাষা',
    'settings.bangla': 'বাংলা',
    'settings.english': 'English',

    // Direct keys for components
    'fullName': 'পূর্ণ নাম',
    'password': 'পাসওয়ার্ড',
    'confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
    'terms': 'শর্তাবলী',
    'privacy': 'গোপনীয়তা নীতি',
    'or': 'অথবা',
    'alreadyHaveAccount': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    'login': 'লগইন',
    'register': 'রেজিস্ট্রেশন',
    'startFree': 'বিনামূল্যে শুরু করুন',
    'viewCourses': 'কোর্স দেখুন',
    'aboutUs': 'আমাদের সম্পর্কে',
    'contact': 'যোগাযোগ',
    'viewAllCourses': 'সব কোর্স দেখুন',
    'classes': 'ক্লাস',
    'teachers': 'শিক্ষক',
    'viewDemo': 'ডেমো দেখুন',
    'youAre': 'আপনি কে?',
    'student': 'শিক্ষার্থী',
    'guardian': 'অভিভাবক',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.courses': 'Courses',
    'nav.batches': 'Batches',
    'nav.students': 'Students',
    'nav.teachers': 'Teachers',
    'nav.guardians': 'Guardians',
    'nav.exams': 'Exams',
    'nav.payments': 'Payments',
    'nav.analytics': 'Analytics',
    'nav.logout': 'Logout',
    'nav.search': 'Search...',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of your educational institution',
    'dashboard.totalStudents': 'Total Students',
    'dashboard.totalTeachers': 'Total Teachers',
    'dashboard.totalCourses': 'Total Courses',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.activeBatches': 'Active Batches',
    'dashboard.upcomingExams': 'Upcoming Exams',
    'dashboard.pendingPayments': 'Pending Payments',
    'dashboard.recentActivities': 'Recent Activities',
    'dashboard.notices': 'Notices',
    'dashboard.popularCourses': 'Popular Courses',
    'dashboard.newStudents': 'New Students',
    'dashboard.viewAll': 'View All',
    
    // Common
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.pending': 'Pending',
    'common.completed': 'Completed',
    'common.upcoming': 'Upcoming',
    'common.all': 'All',
    'common.details': 'Details',
    'common.create': 'Create',
    'common.admin': 'Admin',
    
    // Courses
    'courses.title': 'Course Management',
    'courses.subtitle': 'Manage all your courses here',
    'courses.newCourse': 'New Course',
    'courses.published': 'Published',
    'courses.draft': 'Draft',
    'courses.featured': 'Featured',
    'courses.hsc': 'HSC',
    'courses.ssc': 'SSC',
    'courses.admission': 'Admission Prep',
    'courses.job': 'Job',
    'courses.skill': 'Skill',
    'courses.language': 'Language',
    'courses.allCourses': 'All Courses',
    'courseName': 'Course Name',
    'category': 'Category',
    'price': 'Price',
    'discount': 'Discount',
    'subject': 'Subject',
    'totalClasses': 'Total Classes',
    'students': 'Students',
    'enrolled': 'Enrolled',
    
    // Batches
    'batches.title': 'Batch Management',
    'batches.subtitle': 'Manage all your batches here',
    'batches.newBatch': 'New Batch',
    'batches.ongoing': 'Ongoing',
    'batches.allBatches': 'All Batches',
    'batchName': 'Batch Name',
    'schedule': 'Schedule',
    'room': 'Room',
    'startDate': 'Start',
    'endDate': 'End',
    'maxStudents': 'Max',
    'current': 'Current',
    'sat': 'Sat',
    'sun': 'Sun',
    'mon': 'Mon',
    'tue': 'Tue',
    'wed': 'Wed',
    'thu': 'Thu',
    'fri': 'Fri',
    
    // Students
    'students.title': 'Student Management',
    'students.subtitle': 'Manage all your students here',
    'students.newStudent': 'New Student',
    'studentName': 'Name',
    'roll': 'Roll',
    'class': 'Class',
    'group': 'Group',
    'session': 'Session',
    'email': 'Email',
    'phone': 'Phone',
    'allStudents': 'All Students',
    'suspended': 'Suspended',
    
    // Teachers
    'teachers.title': 'Teacher Management',
    'teachers.subtitle': 'Manage your teachers profiles and information',
    'teachers.newTeacher': 'New Teacher',
    'qualification': 'Qualification',
    'experience': 'Experience',
    'designation': 'Designation',
    'years': 'years',
    
    // Guardian
    'guardian.title': 'Guardian Management',
    'guardian.subtitle': 'Manage students guardian information',
    'guardian.newGuardian': 'New Guardian',
    'occupation': 'Occupation',
    'relation': 'Relation',
    'father': 'Father',
    'mother': 'Mother',
    'other': 'Other',
    'children': 'Children',
    'monthlyIncome': 'Monthly Income',
    
    // Exams
    'exams.title': 'Exam Management',
    'exams.subtitle': 'Manage all your exams here',
    'exams.newExam': 'New Exam',
    'examType': 'Type',
    'mcq': 'MCQ',
    'written': 'Written',
    'practical': 'Practical',
    'mixed': 'Mixed',
    'totalMarks': 'Total Marks',
    'passingMarks': 'Passing Marks',
    'duration': 'Duration',
    'minutes': 'minutes',
    'startExam': 'Start Exam',
    'result': 'Result',
    'questions': 'Questions',
    
    // Payments
    'payments.title': 'Payment Management',
    'payments.subtitle': 'Track student payments',
    'payments.newPayment': 'New Payment',
    'amount': 'Amount',
    'method': 'Method',
    'transactionId': 'Transaction',
    'date': 'Date',
    'due': 'Due',
    'bkash': 'bKash',
    'nagad': 'Nagad',
    'rocket': 'Rocket',
    'bank': 'Bank',
    'cash': 'Cash',
    'card': 'Card',
    'admissionFee': 'Admission Fee',
    'monthlyFee': 'Monthly Fee',
    'examFee': 'Exam Fee',
    'certificateFee': 'Certificate Fee',
    'otherFee': 'Other',
    'failed': 'Failed',
    'refunded': 'Refunded',
    'receipt': 'Receipt',
    'remind': 'Remind',
    'mark': 'Mark',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Detailed analysis of your institution',
    'thisMonth': 'This Month',
    'thisYear': 'This Year',
    'monthlyRevenue': 'Monthly Revenue',
    'attendanceRate': 'Attendance Rate',
    'avgScore': 'Average Score',
    'passRate': 'Pass Rate',
    'topCourses': 'Top Courses',
    'enrollmentByCategory': 'Enrollment by Category',
    'examTrend': 'Exam Result Trend',
    'avgScoreShort': 'Avg',
    'passRateShort': 'Pass',
    'term': 'Term',
    'avgRevenue': 'Avg Revenue',
    
    // Auth
    'auth.welcome': 'Welcome!',
    'auth.loginTitle': 'Sign in to your account',
    'auth.registerTitle': 'Register',
    'auth.loginSubtitle': 'Start free today',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.registerNow': 'Register now',
    'auth.loginNow': 'Login',
    'auth.or': 'Or',
    'auth.remember': 'Remember me',
    'auth.forgotPassword': 'Forgot password?',
    'auth.terms': 'Terms',
    'auth.privacy': 'Privacy Policy',
    'auth.agree': 'I have read and agree to the',
    'auth.whoAreYou': 'Who are you?',
    'auth.student': 'Student',
    'auth.teacher': 'Teacher',
    'auth.guardian': 'Guardian',
    'auth.confirmPassword': 'Confirm Password',
    
    // Landing
    'landing.heroTitle': "Bangladesh's Best",
    'landing.heroSubtitle': 'Online Education Platform',
    'landing.heroDesc': 'Complete preparation for HSC, SSC, University Admission, BCS and Job exams. Learn from the best teachers in the country.',
    'landing.startFree': 'Start Free',
    'landing.viewCourses': 'View Courses',
    'landing.studentsEnrolled': 'students successfully completed courses',
    'landing.whyChoose': 'Why Choose Us?',
    'landing.whyDesc': 'We are committed to providing the best education experience for students in Bangladesh',
    'landing.banglaCourse': 'Courses in Bengali',
    'landing.banglaDesc': 'All content in Bengali, easy to understand for Bangladeshi students',
    'landing.onlineOffline': 'Online + Offline',
    'landing.onlineOfflineDesc': 'Live classes and recorded videos, study even without internet',
    'landing.modernTest': 'Modern Tests',
    'landing.modernTestDesc': 'Prepare with model tests and quizzes following board patterns',
    'landing.expertTeachers': 'Expert Teachers',
    'landing.expertDesc': 'Experienced teachers from top universities and coaching centers',
    'landing.affordable': 'Affordable',
    'landing.affordableDesc': 'Best quality education within reach, payment via bKash/Nagad',
    'landing.certificate': 'Certificate',
    'landing.certificateDesc': 'Get certification after completing courses, valuable in job market',
    'landing.popularCourses': 'Popular Courses',
    'landing.popularDesc': 'View our best courses and start today',
    'landing.viewAllCourses': 'View All Courses',
    'landing.ourTeachers': 'Our Teachers',
    'landing.teachersDesc': 'Experienced teachers from top universities and coaching centers guide your studies',
    'landing.startJourney': 'Start Your Education Journey Today',
    'landing.journeyDesc': 'Thousands of students have already succeeded in our courses. Now it is your turn!',
    'landing.registerFree': 'Register Free',
    'landing.watchDemo': 'Watch Demo',
    'landing.courses': 'Courses',
    'landing.about': 'About',
    'landing.contact': 'Contact',
    'landing.login': 'Login',
    'landing.freeStart': 'Start Free',
    
    // Footer
    'footer.about': "Bangladesh's best online education platform. Complete preparation for HSC, SSC, University Admission and Job Preparation.",
    'footer.hsc': 'HSC Preparation',
    'footer.ssc': 'SSC Preparation',
    'footer.admission': 'University Admission',
    'footer.bcs': 'BCS Preparation',
    'footer.becomeTeacher': 'Become a Teacher',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact',
    'footer.cookies': 'Cookie Settings',
    'footer.copyright': 'All rights reserved.',
    'footer.hscCourses': 'HSC Courses',
    'footer.important': 'Important Links',
    'footer.address': 'Dhaka, Bangladesh',
    
    // Notice types
    'notice.general': 'General',
    'notice.exam': 'Exam',
    'notice.payment': 'Payment',
    'notice.event': 'Event',
    'notice.holiday': 'Holiday',
    'notice.urgent': 'Urgent',
    'notice.high': 'High',
    'notice.medium': 'Medium',
    'notice.low': 'Low',
    
    // Settings
    'settings.language': 'Language',
    'settings.bangla': 'বাংলা',
    'settings.english': 'English',

    // Direct keys for components
    'fullName': 'Full Name',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'terms': 'Terms',
    'privacy': 'Privacy Policy',
    'or': 'Or',
    'alreadyHaveAccount': 'Already have an account?',
    'login': 'Login',
    'register': 'Register',
    'startFree': 'Start Free',
    'viewCourses': 'View Courses',
    'aboutUs': 'About Us',
    'contact': 'Contact',
    'viewAllCourses': 'View All Courses',
    'classes': 'classes',
    'teachers': 'Teachers',
    'viewDemo': 'Watch Demo',
    'youAre': 'Who are you?',
    'student': 'Student',
    'guardian': 'Guardian',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      return (localStorage.getItem('language') as Language) || 'bn';
    }
    return 'bn';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
