import type {
  User,
  Student,
  Teacher,
  Guardian,
  Course,
  Batch,
  Enrollment,
  Exam,
  Payment,
  DashboardStats,
  AnalyticsData,
  Notice,
  Assignment,
  Review,
  Activity,
  Subject,
} from '@/types';

export const teachers: Teacher[] = [
  {
    id: 't1',
    name: 'ড. মোহাম্মদ রহিম',
    email: 'rohim@example.com',
    phone: '01712345678',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    role: 'teacher',
    status: 'active',
    createdAt: '2022-01-15',
    lastLogin: '2026-04-14T09:30:00',
    designation: 'প্রধান শিক্ষক',
    subjects: ['পদার্থবিজ্ঞান', 'গণিত'],
    qualification: 'পিএইচডি, বুয়েট',
    experience: 12,
    courseIds: ['c1', 'c2'],
    rating: 4.9,
    totalStudents: 450,
  },
  {
    id: 't2',
    name: 'ফাতেমা আক্তার',
    email: 'fatema@example.com',
    phone: '01812345678',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    role: 'teacher',
    status: 'active',
    createdAt: '2022-03-20',
    lastLogin: '2026-04-14T08:15:00',
    designation: 'সিনিয়র শিক্ষক',
    subjects: ['রসায়ন', 'উচ্চতর গণিত'],
    qualification: 'এমএসসি, ঢাকা বিশ্ববিদ্যালয়',
    experience: 8,
    courseIds: ['c3', 'c4'],
    rating: 4.8,
    totalStudents: 380,
  },
  {
    id: 't3',
    name: 'আবদুল করিম',
    email: 'karim@example.com',
    phone: '01612345678',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    role: 'teacher',
    status: 'active',
    createdAt: '2021-06-10',
    lastLogin: '2026-04-13T16:45:00',
    designation: 'শিক্ষক',
    subjects: ['জীববিজ্ঞান', 'সাধারণ বিজ্ঞান'],
    qualification: 'এমবিবিএস, ঢাকা মেডিকেল',
    experience: 6,
    courseIds: ['c5'],
    rating: 4.7,
    totalStudents: 290,
  },
  {
    id: 't4',
    name: 'নাজমা বেগম',
    email: 'najma@example.com',
    phone: '01512345678',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    role: 'teacher',
    status: 'active',
    createdAt: '2023-01-05',
    lastLogin: '2026-04-14T10:00:00',
    designation: 'সহকারী শিক্ষক',
    subjects: ['ইংরেজি', 'ভারতীয় ইতিহাস'],
    qualification: 'বিএ, ঢাকা বিশ্ববিদ্যালয়',
    experience: 4,
    courseIds: ['c6', 'c7'],
    rating: 4.6,
    totalStudents: 180,
  },
];

export const students: Student[] = [
  {
    id: 's1',
    name: 'রাহাত হোসেন',
    email: 'rahathossain@student.bd',
    phone: '01912345678',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop',
    role: 'student',
    status: 'active',
    createdAt: '2024-01-10',
    lastLogin: '2026-04-14T11:30:00',
    roll: '001',
    class: ' HSC 1st Year',
    section: 'A',
    group: 'Science',
    session: '2025-26',
    guardianId: 'g1',
    batchIds: ['b1', 'b2'],
    enrollments: [],
    attendance: [],
    payments: [],
    results: [],
  },
  {
    id: 's2',
    name: 'সাবরিনা ইসলাম',
    email: 'sabrinalearn@student.bd',
    phone: '01812345679',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop',
    role: 'student',
    status: 'active',
    createdAt: '2024-02-15',
    lastLogin: '2026-04-14T09:00:00',
    roll: '002',
    class: 'HSC 2nd Year',
    section: 'A',
    group: 'Science',
    session: '2024-25',
    guardianId: 'g2',
    batchIds: ['b1', 'b3'],
    enrollments: [],
    attendance: [],
    payments: [],
    results: [],
  },
  {
    id: 's3',
    name: 'তানভীর আহমেদ',
    email: 'tanvirstudy@student.bd',
    phone: '01712345679',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
    role: 'student',
    status: 'active',
    createdAt: '2023-06-20',
    lastLogin: '2026-04-13T15:20:00',
    roll: '015',
    class: 'SSC',
    section: 'A',
    session: '2025-26',
    guardianId: 'g3',
    batchIds: ['b4'],
    enrollments: [],
    attendance: [],
    payments: [],
    results: [],
  },
  {
    id: 's4',
    name: 'মরিয়ম চৌধুরী',
    email: 'moriyam@student.bd',
    phone: '01612345679',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop',
    role: 'student',
    status: 'active',
    createdAt: '2024-03-01',
    lastLogin: '2026-04-14T08:45:00',
    roll: '003',
    class: 'HSC 1st Year',
    section: 'B',
    group: 'Commerce',
    session: '2025-26',
    guardianId: 'g4',
    batchIds: ['b5'],
    enrollments: [],
    attendance: [],
    payments: [],
    results: [],
  },
  {
    id: 's5',
    name: 'সাকিব রহমান',
    email: 'sakibprep@student.bd',
    phone: '01512345679',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop',
    role: 'student',
    status: 'inactive',
    createdAt: '2023-11-15',
    lastLogin: '2026-03-28T12:00:00',
    roll: '022',
    class: 'HSC 2nd Year',
    section: 'A',
    group: 'Science',
    session: '2024-25',
    guardianId: 'g5',
    batchIds: ['b2'],
    enrollments: [],
    attendance: [],
    payments: [],
    results: [],
  },
];

export const guardians: Guardian[] = [
  {
    id: 'g1',
    name: 'মো. হোসেন আলী',
    email: 'hossainali@guardian.bd',
    phone: '01987654321',
    role: 'guardian',
    status: 'active',
    createdAt: '2024-01-10',
    occupation: 'ব্যবসায়ী',
    relation: 'father',
    studentIds: ['s1'],
    monthlyIncome: 80000,
  },
  {
    id: 'g2',
    name: 'ফাতেমা বেগম',
    email: 'fatema.begum@guardian.bd',
    phone: '01887654321',
    role: 'guardian',
    status: 'active',
    createdAt: '2024-02-15',
    occupation: 'গৃহিনী',
    relation: 'mother',
    studentIds: ['s2'],
    monthlyIncome: 0,
  },
];

export const courses: Course[] = [
  {
    id: 'c1',
    title: 'HSC Physics Complete Course',
    titleBn: 'এইচএসসি পদার্থবিজ্ঞান সম্পূর্ণ কোর্স',
    description: 'HSC Science group students এর জন্য সম্পূর্ণ পদার্থবিজ্ঞান প্রস্তুতি কোর্স। বোর্ড পরীক্ষার পাশাপাশি ভার্সিটি এডমিশন টেস্ট এর জন্যও উপযোগী।',
    descriptionBn: 'এইচএসসি বিজ্ঞান বিভাগের শিক্ষার্থীদের জন্য সম্পূর্ণ পদার্থবিজ্ঞান প্রস্তুতি কোর্স। বোর্ড পরীক্ষা এবং বিশ্ববিদ্যালয় ভর্তি পরীক্ষার জন্য উপযুক্ত।',
    category: 'hsc',
    subject: 'পদার্থবিজ্ঞান',
    teacherId: 't1',
    teacher: teachers[0],
    thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=250&fit=crop',
    price: 8000,
    discount: 15,
    duration: 12,
    durationUnit: 'months',
    totalClasses: 150,
    completedClasses: 89,
    enrolledStudents: 245,
    rating: 4.9,
    reviewCount: 189,
    language: 'bn',
    requirements: [' HSC 1st Year Science', 'মৌলিক গণিত জ্ঞান'],
    outcomes: ['বোর্ড পরীক্ষায় A+ নিশ্চিত', 'ভার্সিটি এডমিশন এ গুড র‌্যাংক', 'পদার্থবিজ্ঞানে দক্ষতা অর্জন'],
    isPublished: true,
    isFeatured: true,
    createdAt: '2024-01-01',
    updatedAt: '2026-04-10',
  },
  {
    id: 'c2',
    title: 'Mathematics for HSC & University Admission',
    titleBn: 'এইচএসসি ও বিশ্ববিদ্যালয় ভর্তি গণিত',
    description: 'HSC Higher Math এবং University admission test এর জন্য comprehensive mathematics course।',
    descriptionBn: 'এইচএসসি উচ্চতর গণিত এবং বিশ্ববিদ্যালয় ভর্তি পরীক্ষার জন্য সম্পূর্ণ গণিত কোর্স।',
    category: 'hsc',
    subject: 'গণিত',
    teacherId: 't1',
    teacher: teachers[0],
    thumbnail: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&h=250&fit=crop',
    price: 7500,
    discount: 10,
    duration: 10,
    durationUnit: 'months',
    totalClasses: 120,
    completedClasses: 72,
    enrolledStudents: 198,
    rating: 4.8,
    reviewCount: 156,
    language: 'bn',
    requirements: ['SSC গণিত জ্ঞান', 'লজিক্যাল থিংকিং'],
    outcomes: ['উচ্চতর গণিতে দক্ষতা', 'এডমিশন টেস্ট পাস', 'Math Olympiad প্রস্তুতি'],
    isPublished: true,
    isFeatured: true,
    createdAt: '2024-01-15',
    updatedAt: '2026-04-08',
  },
  {
    id: 'c3',
    title: 'HSC Chemistry Master Course',
    titleBn: 'এইচএসসি রসায়ন মাস্টার কোর্স',
    description: 'Organic, Inorganic এবং Physical Chemistry সহ সম্পূর্ণ রসায়ন কোর্স।',
    descriptionBn: 'জৈব, অজৈব এবং ভৌত রসায়ন সহ সম্পূর্ণ রসায়ন কোর্স।',
    category: 'hsc',
    subject: 'রসায়ন',
    teacherId: 't2',
    teacher: teachers[1],
    thumbnail: 'https://images.unsplash.com/photo-1532634922-8fe0b757fb63?w=400&h=250&fit=crop',
    price: 7500,
    duration: 10,
    durationUnit: 'months',
    totalClasses: 130,
    completedClasses: 85,
    enrolledStudents: 210,
    rating: 4.8,
    reviewCount: 167,
    language: 'bn',
    requirements: ['HSC Science', 'রসায়নের মৌলিক ধারণা'],
    outcomes: ['রসায়নে বোর্ডে ভালো রেজাল্ট', 'এডমিশন টেস্ট পাস'],
    isPublished: true,
    isFeatured: false,
    createdAt: '2024-02-01',
    updatedAt: '2026-04-05',
  },
  {
    id: 'c4',
    title: 'BUET Admission Test Preparation',
    titleBn: 'বুয়েট ভর্তি পরীক্ষা প্রস্তুতি',
    description: 'Bangladesh University of Engineering and Technology এ ভর্তির জন্য বিশেষ প্রস্তুতি কোর্স।',
    descriptionBn: 'বাংলাদেশ প্রকৌশল বিশ্ববিদ্যালয়ে ভর্তির জন্য বিশেষ প্রস্তুতি কোর্স।',
    category: 'admission',
    subject: 'প্রকৌশল ভর্তি',
    teacherId: 't2',
    teacher: teachers[1],
    thumbnail: 'https://images.unsplash.com/photo-1562774053-701939374585?w=400&h=250&fit=crop',
    price: 15000,
    discount: 20,
    duration: 6,
    durationUnit: 'months',
    totalClasses: 180,
    completedClasses: 120,
    enrolledStudents: 156,
    rating: 4.9,
    reviewCount: 98,
    language: 'bn',
    requirements: ['HSC Science background', 'গণিত ও পদার্থবিজ্ঞানে দক্ষতা'],
    outcomes: ['BUET তে ভর্তি', 'অন্যান্য ইঞ্জিনিয়ারিং বিশ্ববিদ্যালয়ে ভর্তি'],
    isPublished: true,
    isFeatured: true,
    createdAt: '2023-06-01',
    updatedAt: '2026-04-01',
  },
  {
    id: 'c5',
    title: 'Medical Admission Test Complete Guide',
    titleBn: 'মেডিকেল ভর্তি পরীক্ষা সম্পূর্ণ গাইড',
    description: 'Medical College এ ভর্তির জন্য Biology, Chemistry এবং Physics subject গুলোর সম্পূর্ণ প্রস্তুতি।',
    descriptionBn: 'মেডিকেল কলেজে ভর্তির জন্য জীববিজ্ঞান, রসায়ন এবং পদার্থবিজ্ঞানের সম্পূর্ণ প্রস্তুতি।',
    category: 'admission',
    subject: 'মেডিকেল ভর্তি',
    teacherId: 't3',
    teacher: teachers[2],
    thumbnail: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=250&fit=crop',
    price: 12000,
    duration: 8,
    durationUnit: 'months',
    totalClasses: 160,
    completedClasses: 95,
    enrolledStudents: 178,
    rating: 4.7,
    reviewCount: 134,
    language: 'bn',
    requirements: ['HSC Science', ' Biology基础'],
    outcomes: ['Medical College এ ভর্তি', 'MBBS পড়াশোনা প্রস্তুতি'],
    isPublished: true,
    isFeatured: false,
    createdAt: '2023-09-01',
    updatedAt: '2026-03-28',
  },
  {
    id: 'c6',
    title: 'English Proficiency Course',
    titleBn: 'ইংরেজি দক্ষতা কোর্স',
    description: 'IELTS, TOEFL এবং Spoken English সহ সম্পূর্ণ ইংরেজি কোর্স।',
    descriptionBn: 'আইএলটিএস, টোফেল এবং স্পোকেন ইংরেজি সহ সম্পূর্ণ ইংরেজি কোর্স।',
    category: 'language',
    subject: 'ইংরেজি',
    teacherId: 't4',
    teacher: teachers[3],
    thumbnail: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400&h=250&fit=crop',
    price: 5000,
    discount: 25,
    duration: 4,
    durationUnit: 'months',
    totalClasses: 60,
    completedClasses: 45,
    enrolledStudents: 320,
    rating: 4.6,
    reviewCount: 245,
    language: 'bn',
    requirements: ['মৌলিক ইংরেজি জ্ঞান', 'ইচ্ছাশক্তি'],
    outcomes: ['IELTS 7.0+ স্কোর', 'সাবলীল ইংরেজি কথোপকথন', 'বিদেশে পড়াশোনার সুযোগ'],
    isPublished: true,
    isFeatured: true,
    createdAt: '2024-03-01',
    updatedAt: '2026-04-12',
  },
  {
    id: 'c7',
    title: 'BCS Preliminary Exam Preparation',
    titleBn: 'বিসিএস প্রিলি পরীক্ষা প্রস্তুতি',
    description: 'Bangladesh Civil Service preliminary exam এর জন্য সম্পূর্ণ প্রস্তুতি কোর্স।',
    descriptionBn: 'বাংলাদেশ সিভিল সার্ভিস প্রিলিমিনারি পরীক্ষার জন্য সম্পূর্ণ প্রস্তুতি কোর্স।',
    category: 'job',
    subject: 'বিসিএস',
    teacherId: 't4',
    teacher: teachers[3],
    thumbnail: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=250&fit=crop',
    price: 10000,
    duration: 6,
    durationUnit: 'months',
    totalClasses: 100,
    completedClasses: 65,
    enrolledStudents: 275,
    rating: 4.7,
    reviewCount: 198,
    language: 'bn',
    requirements: ['উচ্চমাধ্যমিক বা সমমান', 'সাধারণ জ্ঞান আছে এমন'],
    outcomes: ['বিসিএস পরীক্ষায় উত্তীর্ণ', 'সরকারি চাকরি প্রস্তুতি'],
    isPublished: true,
    isFeatured: false,
    createdAt: '2023-11-01',
    updatedAt: '2026-04-10',
  },
];

export const batches: Batch[] = [
  {
    id: 'b1',
    name: 'HSC 2026 Science - Alpha',
    courseId: 'c1',
    course: courses[0],
    teacherId: 't1',
    teacher: teachers[0],
    startDate: '2025-07-01',
    endDate: '2026-04-30',
    schedule: [
      { day: 'saturday', startTime: '09:00', endTime: '12:00' },
      { day: 'monday', startTime: '09:00', endTime: '12:00' },
      { day: 'wednesday', startTime: '09:00', endTime: '12:00' },
    ],
    maxStudents: 40,
    currentStudents: 38,
    status: 'ongoing',
    roomNumber: '101',
  },
  {
    id: 'b2',
    name: 'HSC 2026 Science - Beta',
    courseId: 'c2',
    course: courses[1],
    teacherId: 't1',
    teacher: teachers[0],
    startDate: '2025-07-01',
    endDate: '2026-04-30',
    schedule: [
      { day: 'sunday', startTime: '14:00', endTime: '17:00' },
      { day: 'tuesday', startTime: '14:00', endTime: '17:00' },
      { day: 'thursday', startTime: '14:00', endTime: '17:00' },
    ],
    maxStudents: 35,
    currentStudents: 32,
    status: 'ongoing',
    roomNumber: '102',
  },
  {
    id: 'b3',
    name: 'HSC 2025 Science - Final',
    courseId: 'c3',
    course: courses[2],
    teacherId: 't2',
    teacher: teachers[1],
    startDate: '2024-07-01',
    endDate: '2025-06-30',
    schedule: [
      { day: 'saturday', startTime: '14:00', endTime: '17:00' },
      { day: 'tuesday', startTime: '09:00', endTime: '12:00' },
    ],
    maxStudents: 40,
    currentStudents: 35,
    status: 'ongoing',
    roomNumber: '103',
  },
  {
    id: 'b4',
    name: 'SSC 2026 Science - Prime',
    courseId: 'c5',
    course: courses[4],
    teacherId: 't3',
    teacher: teachers[2],
    startDate: '2025-01-01',
    endDate: '2026-03-31',
    schedule: [
      { day: 'sunday', startTime: '10:00', endTime: '13:00' },
      { day: 'wednesday', startTime: '10:00', endTime: '13:00' },
    ],
    maxStudents: 45,
    currentStudents: 42,
    status: 'ongoing',
    roomNumber: '104',
  },
  {
    id: 'b5',
    name: 'HSC 2026 Commerce - Business',
    courseId: 'c6',
    course: courses[5],
    teacherId: 't4',
    teacher: teachers[3],
    startDate: '2025-07-01',
    endDate: '2026-06-30',
    schedule: [
      { day: 'monday', startTime: '16:00', endTime: '19:00' },
      { day: 'thursday', startTime: '16:00', endTime: '19:00' },
    ],
    maxStudents: 50,
    currentStudents: 28,
    status: 'ongoing',
    roomNumber: '105',
  },
  {
    id: 'b6',
    name: 'BUET 2026 Engineering - Elite',
    courseId: 'c4',
    course: courses[3],
    teacherId: 't2',
    teacher: teachers[1],
    startDate: '2025-07-01',
    endDate: '2026-06-30',
    schedule: [
      { day: 'saturday', startTime: '15:00', endTime: '19:00' },
      { day: 'sunday', startTime: '15:00', endTime: '19:00' },
      { day: 'tuesday', startTime: '15:00', endTime: '19:00' },
      { day: 'wednesday', startTime: '15:00', endTime: '19:00' },
    ],
    maxStudents: 30,
    currentStudents: 28,
    status: 'ongoing',
    roomNumber: '201',
    onlineLink: 'https://zoom.edu.bd/batch-elite',
  },
];

export const enrollments: Enrollment[] = [
  {
    id: 'e1',
    studentId: 's1',
    student: students[0],
    courseId: 'c1',
    course: courses[0],
    batchId: 'b1',
    batch: batches[0],
    enrolledAt: '2025-06-15',
    status: 'active',
    progress: 65,
  },
  {
    id: 'e2',
    studentId: 's1',
    student: students[0],
    courseId: 'c2',
    course: courses[1],
    batchId: 'b2',
    batch: batches[1],
    enrolledAt: '2025-06-20',
    status: 'active',
    progress: 58,
  },
  {
    id: 'e3',
    studentId: 's2',
    student: students[1],
    courseId: 'c1',
    course: courses[0],
    batchId: 'b1',
    batch: batches[0],
    enrolledAt: '2025-06-18',
    status: 'active',
    progress: 72,
  },
  {
    id: 'e4',
    studentId: 's2',
    student: students[1],
    courseId: 'c3',
    course: courses[2],
    batchId: 'b3',
    batch: batches[2],
    enrolledAt: '2025-07-01',
    status: 'active',
    progress: 45,
  },
  {
    id: 'e5',
    studentId: 's3',
    student: students[2],
    courseId: 'c5',
    course: courses[4],
    batchId: 'b4',
    batch: batches[3],
    enrolledAt: '2025-01-10',
    status: 'active',
    progress: 82,
  },
  {
    id: 'e6',
    studentId: 's4',
    student: students[3],
    courseId: 'c6',
    course: courses[5],
    batchId: 'b5',
    batch: batches[4],
    enrolledAt: '2025-07-05',
    status: 'active',
    progress: 38,
  },
];

export const exams: Exam[] = [
  {
    id: 'ex1',
    title: 'Physics Chapter 1-3 Test',
    courseId: 'c1',
    course: courses[0],
    batchId: 'b1',
    teacherId: 't1',
    type: 'mcq',
    totalMarks: 30,
    passingMarks: 15,
    duration: 30,
    scheduledAt: '2026-04-20T10:00:00',
    endedAt: '2026-04-20T10:30:00',
    status: 'upcoming',
    isPublished: true,
    questions: [],
  },
  {
    id: 'ex2',
    title: 'Mathematics Mid-Term Examination',
    courseId: 'c2',
    course: courses[1],
    batchId: 'b2',
    teacherId: 't1',
    type: 'mixed',
    totalMarks: 100,
    passingMarks: 40,
    duration: 180,
    scheduledAt: '2026-04-25T09:00:00',
    endedAt: '2026-04-25T12:00:00',
    status: 'upcoming',
    isPublished: true,
    questions: [],
  },
  {
    id: 'ex3',
    title: 'Chemistry Weekly Quiz',
    courseId: 'c3',
    course: courses[2],
    batchId: 'b3',
    teacherId: 't2',
    type: 'mcq',
    totalMarks: 20,
    passingMarks: 10,
    duration: 20,
    scheduledAt: '2026-04-15T14:00:00',
    endedAt: '2026-04-15T14:20:00',
    status: 'completed',
    isPublished: true,
    questions: [],
  },
];

export const payments: Payment[] = [
  {
    id: 'p1',
    studentId: 's1',
    student: students[0],
    courseId: 'c1',
    course: courses[0],
    amount: 8000,
    discount: 1200,
    method: 'bKash',
    transactionId: 'BK123456789',
    status: 'completed',
    type: 'admission',
    paidAt: '2025-06-15',
    createdAt: '2025-06-15',
  },
  {
    id: 'p2',
    studentId: 's1',
    student: students[0],
    courseId: 'c2',
    course: courses[1],
    amount: 7500,
    discount: 750,
    method: 'Nagad',
    transactionId: 'ND987654321',
    status: 'completed',
    type: 'admission',
    paidAt: '2025-06-20',
    createdAt: '2025-06-20',
  },
  {
    id: 'p3',
    studentId: 's2',
    student: students[1],
    courseId: 'c1',
    course: courses[0],
    amount: 8000,
    discount: 0,
    method: 'bKash',
    transactionId: 'BK987654321',
    status: 'completed',
    type: 'admission',
    paidAt: '2025-06-18',
    createdAt: '2025-06-18',
  },
  {
    id: 'p4',
    studentId: 's3',
    student: students[2],
    courseId: 'c5',
    course: courses[4],
    amount: 12000,
    discount: 2400,
    method: 'Bank',
    transactionId: 'DBBL20250615001',
    status: 'completed',
    type: 'admission',
    paidAt: '2025-01-10',
    createdAt: '2025-01-10',
  },
  {
    id: 'p5',
    studentId: 's1',
    student: students[0],
    amount: 2000,
    method: 'bKash',
    transactionId: 'BK111222333',
    status: 'pending',
    type: 'monthly',
    dueDate: '2026-04-30',
    createdAt: '2026-04-01',
  },
  {
    id: 'p6',
    studentId: 's4',
    student: students[3],
    courseId: 'c6',
    course: courses[5],
    amount: 5000,
    discount: 1250,
    method: 'Rocket',
    transactionId: 'RK444555666',
    status: 'pending',
    type: 'admission',
    dueDate: '2026-04-20',
    createdAt: '2026-04-10',
  },
];

export const notices: Notice[] = [
  {
    id: 'n1',
    title: 'HSC Model Test Schedule 2026',
    content: 'আসন্ন HSC পরীক্ষার জন্য মডেল টেস্টের সময়সূচি প্রকাশ করা হয়েছে। সকল শিক্ষার্থীদের নির্ধারিত তারিখে উপস্থিত থাকতে হবে।',
    type: 'exam',
    priority: 'high',
    publishedBy: 't1',
    publishedAt: '2026-04-12T10:00:00',
    expiresAt: '2026-05-01',
    targetRoles: ['student', 'guardian'],
  },
  {
    id: 'n2',
    title: 'Eid Holiday Notice',
    content: 'ঈদুল ফিতর উপলক্ষে ১০ এপ্রিল থেকে ২০ এপ্রিল পর্যন্ত সকল ক্লাস বন্ধ থাকবে। ২১ এপ্রিল থেকে নিয়মিত ক্লাস শুরু হবে।',
    type: 'holiday',
    priority: 'medium',
    publishedBy: 'admin',
    publishedAt: '2026-04-05T09:00:00',
    expiresAt: '2026-04-21',
    targetRoles: ['student', 'teacher', 'guardian'],
  },
  {
    id: 'n3',
    title: 'Fee Payment Deadline',
    content: 'এপ্রিল মাসের বেতন জমা দেওয়ার শেষ তারিখ ৩০ এপ্রিল। সময়মতো পেমেন্ট না করলে জরিমানা প্রযোজ্য হবে।',
    type: 'payment',
    priority: 'urgent',
    publishedBy: 'admin',
    publishedAt: '2026-04-01T08:00:00',
    expiresAt: '2026-04-30',
    targetRoles: ['student', 'guardian'],
  },
];

export const assignments: Assignment[] = [
  {
    id: 'a1',
    title: 'Physics Chapter 5 - Problems Set',
    description: 'পদার্থবিজ্ঞান পঞ্চম অধ্যায়ের সমস্যা সমাধান করুন। নির্দেশিকা অনুসরণ করে সমস্ত সমস্যা সমাধান করে জমা দিতে হবে।',
    courseId: 'c1',
    course: courses[0],
    teacherId: 't1',
    dueDate: '2026-04-25T23:59:00',
    totalMarks: 20,
    submissions: [],
  },
  {
    id: 'a2',
    title: 'Mathematics Assignment - Calculus',
    description: 'ক্যালকুলাস অধ্যায় থেকে ১০টি সমস্যা সমাধান করে জমা দিন।',
    courseId: 'c2',
    course: courses[1],
    teacherId: 't1',
    dueDate: '2026-04-22T23:59:00',
    totalMarks: 30,
    submissions: [],
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    courseId: 'c1',
    studentId: 's1',
    student: students[0],
    rating: 5,
    comment: 'স্যারের ক্লাস অসাধারণ! পদার্থবিজ্ঞান এখন আমার প্রিয় বিষয়। বোর্ড পরীক্ষার জন্য সম্পূর্ণ প্রস্তুতি পেয়েছি।',
    createdAt: '2026-03-15',
    replies: [
      {
        id: 'rr1',
        reviewId: 'r1',
        userId: 't1',
        userName: 'ড. মোহাম্মদ রহিম',
        comment: 'ধন্যবাদ রাহাত! তোমার মতো মেধাবী শিক্ষার্থী পেয়ে আমিও খুশি।',
        createdAt: '2026-03-16',
      },
    ],
  },
  {
    id: 'r2',
    courseId: 'c1',
    studentId: 's2',
    student: students[1],
    rating: 5,
    comment: 'সবচেয়ে ভালো পদার্থবিজ্ঞান কোর্স! স্যার অনেক সহজ ভাবে বিষয়গুলো বুঝিয়ে বলেন।',
    createdAt: '2026-03-10',
    replies: [],
  },
];

export const subjects: Subject[] = [
  { id: 'sub1', name: 'Physics', nameBn: 'পদার্থবিজ্ঞান', code: 'PHY', category: 'hsc' },
  { id: 'sub2', name: 'Chemistry', nameBn: 'রসায়ন', code: 'CHEM', category: 'hsc' },
  { id: 'sub3', name: 'Mathematics', nameBn: 'গণিত', code: 'MATH', category: 'hsc' },
  { id: 'sub4', name: 'Higher Mathematics', nameBn: 'উচ্চতর গণিত', code: 'HMATH', category: 'hsc' },
  { id: 'sub5', name: 'Biology', nameBn: 'জীববিজ্ঞান', code: 'BIO', category: 'hsc' },
  { id: 'sub6', name: 'English', nameBn: 'ইংরেজি', code: 'ENG', category: 'hsc' },
  { id: 'sub7', name: 'Bengali', nameBn: 'বাংলা', code: 'BAN', category: 'hsc' },
  { id: 'sub8', name: 'ICT', nameBn: 'তথ্য ও যোগাযোগ প্রযুক্তি', code: 'ICT', category: 'hsc' },
];

export const activities: Activity[] = [
  {
    id: 'act1',
    type: 'enrollment',
    description: 'নতুন শিক্ষার্থী ভর্তি',
    userId: 's1',
    userName: 'রাহাত হোসেন',
    timestamp: '2026-04-14T10:30:00',
  },
  {
    id: 'act2',
    type: 'payment',
    description: 'পেমেন্ট সম্পন্ন',
    userId: 's2',
    userName: 'সাবরিনা ইসলাম',
    timestamp: '2026-04-14T09:15:00',
  },
  {
    id: 'act3',
    type: 'exam',
    description: 'পরীক্ষা সম্পন্ন',
    userId: 's3',
    userName: 'তানভীর আহমেদ',
    timestamp: '2026-04-13T16:45:00',
  },
  {
    id: 'act4',
    type: 'certificate',
    description: 'সনদপত্র প্রদান',
    userId: 's5',
    userName: 'সাকিব রহমান',
    timestamp: '2026-04-12T11:00:00',
  },
  {
    id: 'act5',
    type: 'assignment',
    description: 'অ্যাসাইনমেন্ট জমা',
    userId: 's4',
    userName: 'মরিয়ম চৌধুরী',
    timestamp: '2026-04-11T14:20:00',
  },
];

export const dashboardStats: DashboardStats = {
  totalStudents: 1247,
  totalTeachers: 48,
  totalCourses: 86,
  totalRevenue: 4582000,
  monthlyGrowth: 12.5,
  activeBatches: 24,
  upcomingExams: 8,
  pendingPayments: 156,
};

export const analyticsData: AnalyticsData = {
  revenueByMonth: [
    { month: 'Jan', amount: 320000 },
    { month: 'Feb', amount: 380000 },
    { month: 'Mar', amount: 420000 },
    { month: 'Apr', amount: 395000 },
    { month: 'May', amount: 450000 },
    { month: 'Jun', amount: 480000 },
  ],
  studentEnrollmentByCategory: [
    { category: 'HSC', count: 520 },
    { category: 'SSC', count: 280 },
    { category: 'Admission', count: 310 },
    { category: 'Job', count: 120 },
    { category: 'Skill', count: 85 },
    { category: 'Language', count: 180 },
  ],
  attendanceRate: 87.5,
  examPerformance: [
    { avgScore: 72, passRate: 89 },
    { avgScore: 68, passRate: 85 },
    { avgScore: 75, passRate: 92 },
    { avgScore: 71, passRate: 88 },
    { avgScore: 78, passRate: 94 },
  ],
  topCourses: courses.slice(0, 5),
  recentActivities: activities,
};

export const currentUser: User = {
  id: 'admin1',
  name: 'প্রশাসক',
  email: 'admin@ishkul.edu.bd',
  phone: '01912345678',
  role: 'admin',
  status: 'active',
  createdAt: '2022-01-01',
  lastLogin: '2026-04-14T08:00:00',
};
